default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= Rails.application.credentials.dig(:postgresql, :username) %>
  password: <%= Rails.application.credentials.dig(:postgresql, :password) %>

development:
  <<: *default
  database: my_app_development

test:
  <<: *default
  database: my_app_test

production:
  <<: *default
  database: my_app_production
